require('leo.plugins')
require('leo.sets')
require('leo.keybindings')
require('leo.statusline')
require('leo.lsp')
require('leo.telescope')
require('leo.cmp')
require('leo.dashboard')

vim.cmd('let g:gruvbox_contrast_dark="hard"')
vim.cmd('colorscheme gruvbox')
